import{i,S as l}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function e(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(r){if(r.ep)return;r.ep=!0;const t=e(r);fetch(r.href,t)}})();const d="43214760-0343bbd140b24677312cd0c55";function u(n){const o=`https://pixabay.com/api/?key=${d}&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(o).then(e=>{if(!e.ok)throw new Error("Network response was not ok");return e.json()}).then(e=>e.hits).catch(e=>(console.error("Error fetching images:",e),[]))}function f(){const n=document.getElementById("gallery");n.innerHTML=""}function m(n){const o=document.getElementById("gallery");n.forEach(e=>{const s=document.createElement("div");s.classList.add("card"),s.innerHTML=`
      <a href="${e.largeImageURL}" data-lightbox="gallery-item">
        <img class="contentCard" src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <div class="imgCard">
      <p><b>Likes:</b> ${e.likes}</p>
      <p><b>Views:</b> ${e.views}</p>
      <p><b>Comments:</b> ${e.comments}</p>
      <p><b>Downloads:</b> ${e.downloads}</p></div>
    `,o.appendChild(s)})}const h=document.getElementById("search-form"),y=document.getElementById("search-input"),c=document.querySelector(".loader");h.addEventListener("submit",async n=>{n.preventDefault();const o=y.value.trim();if(!o){i.error({title:"Error",message:"Please enter a keyword for search."});return}c.style.display="block",f();try{const e=await u(o);e.length===0?i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(m(e),new l("[data-lightbox]").refresh())}catch(e){console.error("Error fetching images:",e),i.error({title:"Error",message:"An error occurred while fetching images. Please try again later."})}finally{c.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
