import{i,S as l}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const d="43214760-0343bbd140b24677312cd0c55";async function u(s){const o=`https://pixabay.com/api/?key=${d}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`;return(await(await fetch(o)).json()).hits}function f(){const s=document.getElementById("gallery");s.innerHTML=""}function m(s){const o=document.getElementById("gallery");s.forEach(e=>{const n=document.createElement("div");n.classList.add("card"),n.innerHTML=`
      <a href="${e.largeImageURL}" data-lightbox="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <p>Likes: ${e.likes}</p>
      <p>Views: ${e.views}</p>
      <p>Comments: ${e.comments}</p>
      <p>Downloads: ${e.downloads}</p>
    `,o.appendChild(n)})}const y=document.getElementById("search-form"),p=document.getElementById("search-input"),c=document.querySelector(".loader");y.addEventListener("submit",async s=>{s.preventDefault();const o=p.value.trim();if(!o){i.error({title:"Error",message:"Please enter a keyword for search."});return}c.style.display="block",f();try{const e=await u(o);e.length===0?i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(m(e),new l("[data-lightbox]").refresh())}catch(e){console.error("Error fetching images:",e),i.error({title:"Error",message:"An error occurred while fetching images. Please try again later."})}finally{c.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
